image: ghcr.io/lbssousa/gitpod-workspace-texlive-music:0.0.13
vscode:
  extensions:
    - james-yu.latex-workshop
    - lhl2617.lilypond-formatter
    - lhl2617.lilypond-pdf-preview
    - lhl2617.lilypond-snippets
    - lhl2617.VSLilyPond
    - tecosaur.latex-utilities
    - yzhang.markdown-all-in-one
