name: "Fascículo 4 / Layout A4"
on:
  push:
    branches: [salterio-liturgico]
defaults:
  run:
    working-directory: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Construir PDFs
        uses: lbssousa/latex-music-action@v3.0.0
        with:
          root_file: fasciculo4-a4.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true

      - name: Fazer upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: fasciculo4-a4
          path: |
            *.pdf
            *.log
