name: "Fascículo 1 / Layout A5"
on:
  push:
    branches: [salterio-liturgico]
defaults:
  run:
    working-directory: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Construir PDFs
        uses: lbssousa/latex-music-action@v3.0.0
        with:
          root_file: fasciculo1-a5.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true

      - name: Fazer upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: fasciculo1-a5
          path: |
            *.pdf
            *.log
