name: "Fascículo 4 / Layout A4 alternativo"
on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: .
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Construir PDFs
        uses: lbssousa/lualatex-docker-action@v7
        with:
          directory: 'fasciculo-4'
          file: 'a4-alt'
        env:
          OUT_DIR: public

      - name: Fazer upload dos artefatos
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: public/
